package org.forms.formService.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.forms.formService.cayenne.persistent.Form;

/**
 * Class _FormElement was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FormElement extends CayenneDataObject {

    public static final String COLS_PROPERTY = "cols";
    public static final String CONTENT_PROPERTY = "content";
    public static final String HEIGHT_PROPERTY = "height";
    public static final String NAME_PROPERTY = "name";
    public static final String ROWS_PROPERTY = "rows";
    public static final String TYPE_PROPERTY = "type";
    public static final String WIDTH_PROPERTY = "width";
    public static final String FORM_PROPERTY = "form";

    public static final String ELEMENT_ID_PK_COLUMN = "ElementID";

    public void setCols(Integer cols) {
        writeProperty("cols", cols);
    }
    public Integer getCols() {
        return (Integer)readProperty("cols");
    }

    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }

    public void setHeight(Integer height) {
        writeProperty("height", height);
    }
    public Integer getHeight() {
        return (Integer)readProperty("height");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setRows(Integer rows) {
        writeProperty("rows", rows);
    }
    public Integer getRows() {
        return (Integer)readProperty("rows");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setWidth(Integer width) {
        writeProperty("width", width);
    }
    public Integer getWidth() {
        return (Integer)readProperty("width");
    }

    public void setForm(Form form) {
        setToOneTarget("form", form, true);
    }

    public Form getForm() {
        return (Form)readProperty("form");
    }


}
